import logging
from typing import Any

from openai import AsyncOpenAI

from moonshot.src.connectors.connector import Connector, perform_retry
from moonshot.src.connectors_endpoints.connector_endpoint_arguments import (
    ConnectorEndpointArguments,
)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class OpenAIGpt4(Connector):
    def __init__(self, ep_arguments: ConnectorEndpointArguments):
        # Initialize super class
        super().__init__(ep_arguments)

        # Set OpenAI Key
        self._client = AsyncOpenAI(api_key=self.token)

    @Connector.rate_limited
    @perform_retry
    async def get_response(self, prompt: str) -> str:
        """
        Retrieves and returns a response from the OpenAI GPT-4 API based on the provided prompt.

        This method sends a prompt to the OpenAI GPT-4 API and returns the generated response.
        It is designed to interact with the API, encapsulating both the request sending and response handling
        within the context of this connector instance.

        Args:
            prompt (str): The input prompt to send to the OpenAI API.

        Returns:
            str: The text response generated by the OpenAI GPT-4 model.
        """
        connector_prompt = f"{self.pre_prompt}{prompt}{self.post_prompt}"
        openai_request = [{"role": "user", "content": connector_prompt}]
        response = await self._client.chat.completions.create(
            model="gpt-4",
            messages=openai_request,
            temperature=0,
            timeout=self.timeout,
        )
        return await self._process_response(response)

    async def _process_response(self, response: Any) -> str:
        """
        Processes the response from the OpenAI API, extracting and returning the AI-generated text.

        This method is designed to handle the response from an OpenAI API call, focusing on the chat completion
        response format. It extracts the AI-generated text from the first choice in the response, which is
        the direct output based on the input prompt provided.

        Args:
            response (Any): The response object from an OpenAI API call, expected to conform to the chat
            completion response format.

        Returns:
            str: The AI-generated text extracted from the first choice in the response, representing the
            model's output based on the provided prompt.
        """
        return response.choices[0].message.content
