apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moonshot-mnt-pvc
  namespace: moonshot
spec:
  storageClassName: ebs-gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi