name: ARC Test
on:
  workflow_dispatch:

  push:
    branches: [ ci/sonarcube-sast ]

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-moonshot
    steps:
    - run: echo "This job uses self-hosted runners!"
