name: UAT Build

on:
  # Trigger on merge to main
  push:
    branches:
      - main

  # Run this workflow manually from Actions tab
  workflow_dispatch:
    inputs:
      branch_to_test:
        description: 'Branch or tag to build package'
        required: true
        default: 'main'
        type: string

# Allow one concurrent deployment
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-python-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch_to_test || 'main' }}
          submodules: recursive

      - name: Setup python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Bump version
        run: |
          echo "Bumping version..."
          pip install bump2version
          bump2version patch

      - name: Package test PyPI
        run: |
          echo "Packaging test PyPI..."
          pip install build
          python3 -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package
          path: dist/

  publish-to-testpypi:
    needs:
      - build-python-package
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download python package
        uses: actions/download-artifact@v3
        with:
          name: python-package
          path: dist/

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
